# permissions for end users to edit globalpythonpackages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: globalpythonpackage-editor-role
rules:
- apiGroups:
  - pythonpackage.github.io
  resources:
  - globalpythonpackages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pythonpackage.github.io
  resources:
  - globalpythonpackages/status
  verbs:
  - get
